# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwwebserver
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: ayuuub/k8s-webserver:v2
        imagePullPolicy: IfNotPresent
        name: phpweb
        ports:
        - containerPort: 80
---
# APP SERVICE
apiVersion: v1
kind: Service
metadata:
  name: wwwwebserver
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

